import Header from "@/components/Header";
import "./globals.css";
import {Montserrat} from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrant = Montserrat({
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrant.className}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
